# Generated by Django 6.0.1 on 2026-03-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=20)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carmodel')),
            ],
        ),
    ]
