# Generated by Django 6.0.1 on 2026-03-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_carcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcolor',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carbrand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carcolor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carmodel')),
            ],
        ),
    ]
