# Generated by Django 6.0.1 on 2026-03-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_carcolor_stock_quantity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_models/'),
        ),
    ]
