# Generated by Django 6.0.1 on 2026-03-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_carmodel_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='preview_mask',
            field=models.ImageField(blank=True, help_text='PNG aligned with preview: car body = white/opaque, background = transparent.', null=True, upload_to='car_masks/'),
        ),
    ]
