# Generated by Django 6.0.1 on 2026-03-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_carmodel_preview_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='preview_mask',
            field=models.ImageField(blank=True, help_text='PNG same size/crop as preview. White/opaque ONLY on painted metal/plastic body (hood, doors, fenders, roof). Leave transparent over glass, wheels, tires, grille, headlights, chrome trim, mirrors, and black plastic—otherwise color will bleed there.', null=True, upload_to='car_masks/'),
        ),
    ]
