# Generated by Django 6.0.1 on 2026-03-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_carmodel_preview_mask_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='preview_mask',
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.booking'),
        ),
    ]
