# Generated by Django 6.0.1 on 2026-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_carmodel_preview_mask_alter_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcolor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carcolor',
            name='color_code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='carcolor',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
