# Generated by Django 6.0.1 on 2026-04-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('color', 'Color Product'), ('service', 'Service'), ('custom', 'Custom Car')], default='color', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.service'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.carcolor'),
        ),
    ]
