# Generated by Django 6.0.1 on 2026-04-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_cartitem_custom_config_cartitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='mainapp.customer')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('customer', 'car_model')},
            },
        ),
        migrations.CreateModel(
            name='SavedCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carmodel')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.carcolor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_customizations', to='mainapp.customer')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('customer', 'car_model', 'color')},
            },
        ),
    ]
